spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: TRACE
    org.springframework.orm.jpa: DEBUG